### ISSUE TITLE
[Bug]: New Install--- RuntimeError: Torch is not able to use GPU

### ISSUE THREAD

**Issue by enleo0214** [lshqqytiger/stable-diffusion-webui-directml#340]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

![412596768_7270923466273846_5145939658649481593_n](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/154822915/e444def7-9551-4b3d-a8cf-3a5afc9c23bf)

### Steps to reproduce the problem

https://community.amd.com/t5/ai/updated-how-to-running-optimized-automatic1111-stable-diffusion/ba-p/630252
by this tutorial

### What should have happened?

.

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

.

### Console logs

```Shell
.
```

### Additional information

Deleted venv and tmp
Completely deleted Stable Diffusion WebUI and recloned
Reinstalled python 3.10.6
--use-directml
 --skip-torch-cuda-test

all of them didn't work :(

**Comment by rexorp** [comment]
Read fix here:
https://github.com/lshqqytiger/stable-diffusion-webui-directml/issues/335#issuecomment-1868913108

**Comment by Synergyart** [comment]
Hey there!
The same thing happened to me, this is what fixed the problem:

-Clone SD again on a different folder.
-Open and add on 'requirements_versions.txt' the following: torch-directml.
-On webui-user add '--use-directml' on set COMMANDLINE_ARGS=
-Run webui-user.

It should continue with the install without problems.

**Comment by Foxtrot-Uniform42** [comment]
> Hey there! The same thing happened to me, this is what fixed the problem:
> 
> -Clone SD again on a different folder. -Open and add on 'requirements_versions.txt' the following: torch-directml. -On webui-user add '--use-directml' on set COMMANDLINE_ARGS= -Run webui-user.
> 
> It should continue with the install without problems.

fixed issue for me too

**Comment by cesarcwb98** [comment]
> Hey there! The same thing happened to me, this is what fixed the problem:
> 
> -Clone SD again on a different folder. -Open and add on 'requirements_versions.txt' the following: torch-directml. -On webui-user add '--use-directml' on set COMMANDLINE_ARGS= -Run webui-user.
> 
> It should continue with the install without problems.

fixed for me too

**Comment by lshqqytiger** [comment]
https://github.com/lshqqytiger/stable-diffusion-webui-directml/discussions/334#discussioncomment-7936839

**Comment by sensitive-squid** [comment]
> Hey there! The same thing happened to me, this is what fixed the problem:
> 
> -Clone SD again on a different folder. -Open and add on 'requirements_versions.txt' the following: torch-directml. -On webui-user add '--use-directml' on set COMMANDLINE_ARGS= -Run webui-user.
> 
> It should continue with the install without problems.

This didn't work for me. When I did that I got an error, do you see something that I'm doing wrong?
![Screenshot 2024-01-01 061155](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/155372326/64bae2a3-86a7-40fa-a614-6486636e9553)

**Comment by lshqqytiger** [comment]
Python 3.11 is not supported. Downgrade to <= 3.10

**Comment by micbusin** [comment]
Running webui-user.bat one time with _set COMMANDLINE_ARGS=--use-directml --update-check --update-all-extensions --reinstall-xformers --reinstall-torch_ solved it.
After this you can run it with set COMMANDLINE_ARGS=--use-directml. Or you can keep update options.

**Comment by MonsterAlex** [comment]
> Hey there! The same thing happened to me, this is what fixed the problem:
> 
> -Clone SD again on a different folder. -Open and add on 'requirements_versions.txt' the following: torch-directml. -On webui-user add '--use-directml' on set COMMANDLINE_ARGS= -Run webui-user.
> 
> It should continue with the install without problems.

fixed for me too

**Comment by dlasher** [comment]
AMD support appears to be broken badly under both linux and windows at the moment, fresh OS install, fresh GIT install.

```
RuntimeError: Torch is not able to use GPU
```

Hoping this gets addressed.

**Comment by rvxfahim** [comment]
> Running webui-user.bat one time with _set COMMANDLINE_ARGS=--use-directml --update-check --update-all-extensions --reinstall-xformers --reinstall-torch_ solved it. After this you can run it with set COMMANDLINE_ARGS=--use-directml. Or you can keep update options. Without anything like skipcuda, nohalf, medvram, etc RX 6600 2.2it/s on SD1.5 models. You can list args with _python launch.py --help._

did not fix for me

**Comment by micbusin** [comment]
You can try _pip uninstall torch tochvision_ then _pip install torch-directml_ . I had enough from win and webui, I moved to fedora39 + rocm + comfyui. Now I can run 1024x1024 SDXL generation with a 8GB Radeon6600. So A1111, sdwebui is not an option for me anymore. If you can't fix it I suggest you to do the same. Fedora 40 will have rocm6 out of box. Ubuntu freezed many times because of oom, fedora also unloads models to ram and can reach 100% ram usage, but instead of freezing it just slows down for a while. This happens only when I'm using faceswapping addons with comfy, normal generation always runs smooth.

**Comment by TigermanUK** [comment]
I had my rx580 on win10 updated from 1.4.0 to 1.7.0 and now only the CPU was being used which is about 15x slower than the previously working GPU.  The fixes listed here worked from me as well as another comment above.  Thanks guys...
1)  As Synergyart commented above 

> Hey there!
> The same thing happened to me, this is what fixed the problem:
> 
> -Clone SD again on a different folder.
> -Open and add on 'requirements_versions.txt' the following: torch-directml.
> -On webui-user add '--use-directml' on set COMMANDLINE_ARGS=

I also had to add the line in webui-user.bat '--reinstall-torch' onto    set COMMANDLINE_ARGS=

after the torch requirement was updated i removed the '--reinstall-torch'   otherwise you get the warning every time requirement already met, you don't need to keep seeing this.

Finally I now set my   set COMMANDLINE_ARGS= to the following in webui-user.bat

set COMMANDLINE_ARGS=--medvram --no-half --disable-nan-check --precision full --use-directml --opt-split-attention 

Although from what I am reading some of these command line options may be set in settings in future/now.  But its working for me..    The plus side is iterations per sec went from 1 per second to 1.7its per second.   The downsize the vram is less and less so the dimension you can use keep shrinking.   Prior to 1.4 I could the width and height to 512x512 and it would only run out of vram with too many lora.  After v1.4 if I set the width x height above 464x512 it can't allocate enough mem.  Now with V1.7.0 it looks like I can barely go over 400x400 or results in allocate out of vram error.  So I can't load up old projects that required a bigger starting resolution or as you guys know it will change the output if set width or height different.  Just a small note for others who may have similar experiences...  Code optimization in the last 8 months looks to be great but at the cost of the vram...  If anyone wants to suggest settings that I need to look at are very welcome.  Cheers.

**Comment by dylanh724** [comment]
Followed these to the "T" on a Zephyrus G14:

> RuntimeError: Torch is not able to use GPU

* On this branch
* Added torch-directml
* Copy and pasted everything asked for accuracy

No dice. Does not work on AMD GPU.

**Comment by lshqqytiger** [comment]
remove `venv` folder and run these commands:
```
git stash
git stash clear
git pull
git checkout tags/v1.9.3-amd
```
Don't modify requirements.txt. Just launch webui with `--use-directml`
