### ISSUE TITLE
[Bug]: stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai directory only a .git file after run failed

### ISSUE THREAD

**Issue by ghost** [lshqqytiger/stable-diffusion-webui-directml#94]
### Is there an existing issue for this?

- [x] I have searched the existing issues and checked the recent builds/commits

### What happened?

stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai directory only a .git file after run failed

### Steps to reproduce the problem

1. Run webui-user.bat
2. run failed,and go to repositories\stable-diffusion-stability-ai
3. This directory is only a .git file

### What should have happened?

Such as #4

### Commit where the problem happens

Installing requirements for Web UI

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
No
```

### List of extensions

No

### Console logs

```Shell
venv "venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Commit hash: fd59537df9420bb14c1d6330ec59e30ce870a481
Installing requirements for Web UI
Launching Web UI with arguments:
Traceback (most recent call last):
  File "C:\Users\Administartor\stable-diffusion-webui-directml\launch.py", line 353, in <module>
    start()
  File "C:\Users\Administartor\stable-diffusion-webui-directml\launch.py", line 344, in start
    import webui
  File "C:\Users\Administartor\stable-diffusion-webui-directml\webui.py", line 16, in <module>
    from modules import paths, timer, import_hook, errors
  File "C:\Users\Administartor\stable-diffusion-webui-directml\modules\paths.py", line 19, in <module>
    assert sd_path is not None, "Couldn't find Stable Diffusion in any of: " + str(possible_sd_paths)
AssertionError: Couldn't find Stable Diffusion in any of: ['C:\\Users\\Administartor\\stable-diffusion-webui-directml\\repositories/stable-diffusion-stability-ai', '.', 'C:\\Users\\Administartor']
```

### Additional information

You can  
```
git clone https://github.com/lshqqytiger/stablediffusion-directml.git
```
in the stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai to fix it

**Comment by MedDeatH** [comment]
similar thing with k_diffusion

**Comment by lshqqytiger** [comment]
#46
Or you can use vladmandic's fork.

**Comment by TeutonJon78** [comment]
I think this is an issue in the launch.py script. Rather than defining the correct repo locations, they are trying to reinstall them into the BLIP one.

In launcher.py function "def prepare_environment():"

stable_diffusion_repo = os.environ.get('STABLE_DIFFUSION_REPO', "https://github.com/Stability-AI/stablediffusion.git")
and
k_diffusion_repo = os.environ.get('K_DIFFUSION_REPO', 'https://github.com/crowsonkb/k-diffusion.git')

was switched to

sd_repo = os.environ.get('BLIP_REPO', 'https://github.com/lshqqytiger/stablediffusion-directml.git')
and
k_diffusion_repo = os.environ.get('BLIP_REPO', 'https://github.com/lshqqytiger/k-diffusion-directml.git')
